name: Deploy website to Heroku
on:
    push:
        branches:
            - main
jobs:
    deploy:
        # runs-on: self-hosted
        runs-on: ubuntu-latest
        steps:
            - name: Init project
              uses: actions/checkout@v2
            - run: npm ci
            - name: Deploy to Heroku
              uses: akhileshns/heroku-deploy@v3.5.6
              with:
                heroku_api_key: ${{secrets.API_KEY}}
                heroku_app_name: ${{secrets.APP_NAME}}
                heroku_email: ${{secrets.EMAIL}}
                